### ISSUE TITLE
Code Review - RateMyEPFL

### ISSUE THREAD

**Issue by ros-dorian** [LesGolems/RateMyEPFL#284]
# Code review - RateMyEPFL
This is a code review for the code of the whole project on the main branch at commit https://github.com/LesGolems/RateMyEPFL/tree/96332b11f592b85efd936cf88068124fe8af04d8

Of course, we don't expect you to change all of your code (some parts of the review can be subjective or arguable anyway), what’s important is that you understand why better alternatives may exist.

Please ask us if you have any question about the code review, whether it is by writing a comment below or by sending us an email or meeting us.

**Important : if you try to fix these, don't break your app. We prefer that the app works even if you don't manage to fix anything. It may be too hard to rework many of the issues below, as it would require to rewrite the whole architecture.**

### Package structure

Your package structure really makes sense. One thing maybe could be to create some top-level packages to group some related subpackages. E.g., all UI related packages could be grouped into one big `ui` or `views` package and `database` and `auth` could be grouped into a `backend` package. You could also add a new `service` package for all Android services. Finally, consider putting your Firebase repository implementations in a subpackage `firebase`.

### Documentation

Some parts of the code are more documented than others. In general, a documentation header at the top of every class describing its purpose should be the minimum amount of required documentation. Furthermore, if you decide to write more documentation, focus on the public interfaces of the main systems of your application.

### Code style and quality

The style and quality of your codebase is very consistent and clean. Don’t forget to check the built-in Android Studio linter for additional quick fixes that improve the overall quality.

#### `OccupancyService.kt`

You could consider replacing the `isClose` logic with a distance computation. This would let you define a custom “detection radius”. You can check out the [haversine formula](https://en.wikipedia.org/wiki/Haversine_formula) if you are interested.

#### `PermissionUtils.kt`

The `startPhoneFeature` does not accurately describe what is actually going on. Consider alternatives like `executeOrAskPermissions` or `verifyPermissionAndExecute`.

#### `Channel.kt`

This class contains too much functionality for a data model. Consider either moving this class in the `database` package or moving the functionality to a repository.

#### `Displayable.kt`

The name of this class is not well chosen. Consider renaming it to something that better describes its purpose.

#### `RoomReviewInfoFragment.kt`

Line 35-40, try to avoid calling `findViewById` in a callback. Consider caching the element references instead.

#### `RestaurantReviewInfoFragment.kt`

Same thing as for `RoomReviewInfoFragment.kt`.

#### `EventReviewInfoFragment.kt`

Same thing as for `RoomReviewInfoFragment.kt`.

#### `CourseReviewInfoFragment.kt`

Same thing as for `RoomReviewInfoFragment.kt`.

#### `TimetableFragment.kt`

Line 39-44: Replace with a shorter if expression for readability.

#### `AddClassFragment.kt`

There is no real way of knowing if adding a class to the repository through the viewmodel was successful or not. Consider utilizing Kotlin coroutines to handle this. (This might also be a problem in other views).

#### `UserRepository.kt`

The interface depends on Firebase specific code which defeats the purpose of an abstraction. Consider replacing the semantic of the asynchronous functions to make use of Kotlin’s coroutines (much like `ReviewRepository.kt`).

#### `RoomNoiseRepository.kt`

Same thing as for `UserRepository.kt`.

#### `Repository.kt`

Same thing as for `UserRepository.kt`

#### `GradeInfoRepository.kt`

Same thing as for `UserRepository.kt`

#### `ImageStorage.kt`

As this is a Firebase specific implementation, consider renaming to `FirebaseImageStorage.kt`.

#### `IChannel.kt`

The data contained in a channel and the actual functional interface should be split. Data goes into the `models` package and functionality goes in the repository. 

#### `query` package

The issue with replicating the Firebase API in order to be able to “abstract” it is that you end up with an API that still has the same semantics as Firebase and would be hard to implement with other providers. Moreover, you still have some dependencies to Firebase under the hood which defeat the purpose of the abstraction. It would probably be simpler to use the Firebase objects directly and to use other common APIs (Kotlin coroutines, Futures) in the public interfaces.

#### `SplashScreen.kt`

Consider creating a viewmodel for this view.

## Testing

The package structure and some class names are not always consistent with the source code but other than that you have very extensive tests.

## Conclusion

Beside the few minor comments, you did an excellent job. The architecture is very clean and easy to understand. Great job!

**Comment by mbouilloud** [comment]
Closing this issue as we fixed most of the comments.
